import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getUsername } from "../utils/TokenStorage";

// ✅ No Navbar or Footer imports — Layout in App.jsx handles both

export default function Dashboard() {
  const [username, setUsername] = useState("");

  useEffect(() => {
    setUsername(getUsername() || "User");
  }, []);

  return (
    <>
      <div className="section-header">
        <div>
          <h2 className="section-title">Welcome back, {username}</h2>
          <p style={{ color: "#6b7280", fontSize: 14, marginTop: 4 }}>
            Track your health and get AI-powered recommendations
          </p>
        </div>
      </div>

      <div className="dashboard-grid">

        <Link to="/health" className="dashboard-card" style={{ borderTopColor: "#1d6e8f" }}>
          <div className="dashboard-card-icon">🏃</div>
          <h3 className="dashboard-card-title">Health Metrics</h3>
          <p className="dashboard-card-desc">
            Record your weight, BMI, heart rate, and blood pressure.
            Log physical activities linked to each health session.
          </p>
          <span className="dashboard-card-cta">Open →</span>
        </Link>

        <Link to="/recommendations" className="dashboard-card" style={{ borderTopColor: "#1D9E75" }}>
          <div className="dashboard-card-icon">🤖</div>
          <h3 className="dashboard-card-title">AI Recommendations</h3>
          <p className="dashboard-card-desc">
            Get personalized health recommendations generated by AI
            based on your latest metrics and activities.
          </p>
          <span className="dashboard-card-cta" style={{ color: "#1D9E75" }}>
            Generate →
          </span>
        </Link>

      </div>
    </>
  );
}